# Generated by Django 3.2.5 on 2021-08-22 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(null=True, verbose_name='الإجابة')),
                ('optional_answer', models.TextField(null=True, verbose_name='الإجابة')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
            ],
            options={
                'ordering': ['question__id'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ الانشاء ')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='انشئت بواسطة')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.form')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'تم الرد'), (2, 'لم يتم الرد'), (3, 'مشغول'), (4, 'مغلق أو غير متاح')])),
                ('summary', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.instance')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.instance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=50, verbose_name='عنوان السؤال')),
                ('question_type', models.IntegerField(choices=[(1, 'نص قصير'), (2, 'نص طويل'), (3, 'اختيار متعدد '), (4, 'واحد من متعدد'), (5, 'رقم تليفون')])),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.form', verbose_name='المنوذج')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50, verbose_name='الاختيار')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.question', verbose_name='السؤال')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
            ],
        ),
        migrations.DeleteModel(
            name='From',
        ),
        migrations.AddField(
            model_name='instance',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Form.status'),
        ),
        migrations.AddField(
            model_name='answer',
            name='instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Form.instance'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.question', verbose_name='السؤال'),
        ),
    ]
