# Generated by Django 3.2.5 on 2021-08-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_rename_from_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='حذف'),
        ),
    ]
