# Generated by Django 3.2.5 on 2021-08-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0002_auto_20210822_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='optional_answer',
            field=models.TextField(blank=True, null=True, verbose_name=' (اختيار من متعدد)الإجابة'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_answer',
            field=models.TextField(blank=True, null=True, verbose_name='الإجابة'),
        ),
        migrations.AlterField(
            model_name='instancecall',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='instancecomment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instancecomment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
