# Generated by Django 3.2.5 on 2021-08-26 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Form', '0003_auto_20210825_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.instancecall', verbose_name='Call')),
                ('call_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.instance', verbose_name='Answer')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.instancecomment', verbose_name='Note')),
            ],
        ),
    ]
