# Generated by Django 3.2.5 on 2021-08-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0003_form_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.TextField(default='طلب', verbose_name='تفاصيل النموذج'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان النموذج'),
        ),
    ]
