# Generated by Django 3.2.5 on 2021-08-05 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0004_auto_20210805_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=50, verbose_name='عنوان السؤال')),
                ('question_type', models.CharField(choices=[('نص قصير', 'نص قصير'), ('نص طويل', 'نص طويل'), ('اختيار متعدد', 'اختيار متعدد '), ('واحد من متعدد ', 'واحد من متعدد')], max_length=50)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.form', verbose_name='المنوذج')),
            ],
        ),
    ]
