# Generated by Django 3.2.5 on 2021-08-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0004_callhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callhistory',
            name='note',
        ),
    ]
