# Generated by Django 3.2.5 on 2021-08-05 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0005_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50, verbose_name='الاختيار')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.question', verbose_name='السؤال')),
            ],
        ),
    ]
