# Generated by Django 3.2.5 on 2021-08-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0005_remove_callhistory_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='callhistory',
            name='call_type',
            field=models.IntegerField(choices=[(1, 'Add Call'), (2, 'Edit Call'), (3, 'Delete Call')], default=1, verbose_name='نوع العملية'),
            preserve_default=False,
        ),
    ]
