# Generated by Django 3.2.5 on 2021-08-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0006_questionoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.CharField(max_length=100, verbose_name='تفاصيل النموذج'),
        ),
    ]
