# Generated by Django 3.2.5 on 2021-08-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0007_callhistory_add_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancecall',
            name='call_type',
            field=models.IntegerField(choices=[(1, 'مكالمة صادرة'), (2, 'مكالمة واردة'), (3, 'Whatsapp'), (4, 'Messenger')], default=1, verbose_name='نوع المكالمة'),
            preserve_default=False,
        ),
    ]
