# Generated by Django 3.2.5 on 2021-08-09 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0007_alter_form_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='الإجابة')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.question', verbose_name='السؤال')),
            ],
        ),
    ]
