# Generated by Django 3.2.5 on 2021-08-09 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0008_auto_20210809_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='text_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='optional_answer',
            field=models.ManyToManyField(to='Form.QuestionOption', verbose_name='الإجابة'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'نص قصير'), (2, 'نص طويل'), (3, 'اختيار متعدد '), (4, 'واحد من متعدد')]),
        ),
        migrations.CreateModel(
            name='AnswerPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.form')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Form.answerperson'),
        ),
    ]
