# Generated by Django 3.2.5 on 2021-08-28 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Form', '0008_instancecall_call_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='optional_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_answer',
            field=models.TextField(blank=True, null=True, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='callhistory',
            name='call_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='form',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='form',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='form',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Form Description'),
        ),
        migrations.AlterField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Form Title'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.form', verbose_name='Form'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='Is Submitted?'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Form.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='instancecall',
            name='call_type',
            field=models.IntegerField(choices=[(1, 'مكالمة صادرة'), (2, 'مكالمة واردة'), (3, 'Whatsapp'), (4, 'Messenger'), (5, 'E-Mail')], verbose_name='Call Type'),
        ),
        migrations.AlterField(
            model_name='instancecall',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='instancecall',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='instancecall',
            name='status',
            field=models.IntegerField(choices=[(1, 'Answered'), (2, 'Not Answered'), (3, 'Busy'), (4, 'Unreachable')], verbose_name='Call Status'),
        ),
        migrations.AlterField(
            model_name='instancecall',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Call Summary'),
        ),
        migrations.AlterField(
            model_name='instancecall',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='instancecomment',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='instancecomment',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='question',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_name',
            field=models.CharField(max_length=50, verbose_name='Question Title'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'نص قصير'), (2, 'نص طويل'), (3, 'اختيار متعدد '), (4, 'واحد من متعدد'), (5, 'رقم تليفون'), (5, 'بريد إلكتروني')], verbose_name='Question Type'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='option',
            field=models.CharField(max_length=50, verbose_name='Option'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='status',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Delete'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Status Name'),
        ),
    ]
