# Generated by Django 3.2.5 on 2021-08-11 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0009_auto_20210809_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='person',
        ),
        migrations.AddField(
            model_name='answer',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Form.form'),
        ),
    ]
