# Generated by Django 3.2.5 on 2021-08-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0010_auto_20210811_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='optional_answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='optional_answer',
            field=models.TextField(default=1, verbose_name='الإجابة'),
            preserve_default=False,
        ),
    ]
