# Generated by Django 3.2.5 on 2021-08-15 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0011_auto_20210811_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.form')),
            ],
        ),
        migrations.RemoveField(
            model_name='answer',
            name='form',
        ),
        migrations.AlterField(
            model_name='answer',
            name='optional_answer',
            field=models.TextField(null=True, verbose_name='الإجابة'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text_answer',
            field=models.TextField(null=True, verbose_name='الإجابة'),
        ),
        migrations.DeleteModel(
            name='AnswerPerson',
        ),
        migrations.AddField(
            model_name='answer',
            name='instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Form.instance'),
        ),
    ]
