# Generated by Django 3.2.5 on 2021-08-21 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Form', '0012_auto_20210815_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='حذف'),
        ),
        migrations.AddField(
            model_name='instance',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instance',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='حذف'),
        ),
        migrations.AddField(
            model_name='question',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='حذف'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='حذف'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'نص قصير'), (2, 'نص طويل'), (3, 'اختيار متعدد '), (4, 'واحد من متعدد'), (5, 'رقم تليفون')]),
        ),
        migrations.CreateModel(
            name='InstanceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.instance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstanceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'تم الرد'), (2, 'لم يتم الرد'), (3, 'مشغول'), (4, 'مغلق أو غير متاح')])),
                ('summary', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.instance')),
            ],
        ),
        migrations.AddField(
            model_name='instance',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Form.status'),
        ),
    ]
