# Generated by Django 3.2.5 on 2021-08-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0002_branch_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'default_permissions': (), 'ordering': ['id'], 'permissions': (('add_branch', 'إضافة فرع'), ('edit_branch', 'تعديل فرع'), ('delete_branch', 'حذف فرع'), ('list_branches', 'عرض الفروع'))},
        ),
    ]
